name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref}}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "Package.swift"
      - "**/*.swift"
      - "**/*.xcstrings"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "Package.swift"
      - "**/*.swift"
      - "**/*.xcstrings"
  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Validate XCStrings
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          set -euo pipefail
          changed_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.xcstrings$' || true)
          if [ -z "$changed_files" ]; then
            echo "No modified .xcstrings files."
            exit 0
          fi
          for file in $changed_files; do
            echo "Validating $file"
            python3 -m json.tool "$file" > /dev/null
          done

      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict

  build:
    runs-on: macos-26
    needs: static_analysis
    steps:
      - uses: actions/checkout@v6

      # Issues with other Xcode versions, so we need to specify the version explicitly
      - run: sudo xcode-select -s /Applications/Xcode_26.5.app/Contents/Developer

      - name: Build and Test
        run: |
          xcodebuild test \
            -project Thaw.xcodeproj \
            -scheme Thaw \
            -derivedDataPath Build/ \
            -destination 'platform=macOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
